### ISSUE TITLE
Single queue being unavailable raises exception

### ISSUE THREAD

**Issue by deppy** [ryanhiebert/hirefire#35]
We had an issue the last 2 days where we made 1 of our RabbitMQ servers go down and as soon as it came back, the primary was sync'ing data to the other node.  Unfortunately during that time period, nothing can consume from that queue and because of that all of our autoscaling is put on hold until the queue is fully sync'ed.  I'll take a look but it seems like a simple case of catching the exception and then excluding that from the /info call so that Hirefire properly reports only the 1 queue is experiencing problems but autoscaling can continue for all the other queues.

**Comment by ryanhiebert** [comment]
Would you mind giving me a bit more information about your environment? Since you're using RabbitMQ, does that mean that you're using Celery?

Here's what I'm guessing the situation is from your above comment. Please correct any error. You have a replicated RabbitMQ cluster. During reconstruction, the queues become unavailable one at a time, and HireFire just can't deal with any queue being unavailable. It makes sense to me that in that case it may be reasonable for HireFire to simply skip the unavailable queue(s), and report on whatever queues it is able to figure out.

The way I would implement this is to add a new exception, `QueueUnavailable`, and raise that in the `quantity` method if the queue(s) configured are not available. Then the `hirefire.procs.native_dump_procs` would handle that exception, and simply ignore any proc that raised that exception.

I'm not able to implement this myself, because I don't control a RabbitMQ cluster to test this with, so that I can track it down and ensure that it's correct, and because time is lacking and I'm quite frankly not likely to get to it in the near future.

Still, the use-case makes sense to me, assuming that I've understood it right, and I'd be happy to review pull requests to help get this feature added.

**Comment by deppy** [comment]
Yes, we're using Celery workers and have a mix of Redis+RabbitMQ.   Your guess on the situation seems correct.  It's only during replication when the queue is unavailable that the entire info request results in a 5xx.

I'll look into getting a fix added.  Just wanted to at least document that this was happening.  Luckily the replication events happen so few and far between that there isn't any immediate need for this to happen on my end.  Although I'm sure if we have this happen during a time period that we need upscale to happen, I'll be pushed to submit a PR faster :-)

**Comment by ryanhiebert** [comment]
I'm still on board with designing a solution to this issue, but I don't anticipate having impetus to drive it forward myself. If somebody comes along that would like to implement it, the idea has my blessing! This issue is now quite stale, so I'm going to close it until somebody cares about it enough to do some work on it.
