### ISSUE TITLE
private message's  user A to user B only

### ISSUE THREAD

**Issue by rahul6612** [ryanhiebert/hirefire#38]
hii i want to create a app using django channels to send message from user A to user B so that only B will get the message (and B can reply my message). means to whom i want to send message only that person got my message not group of peoples (like facebook does) for this what i have to do please tell me in simple language bcoz i am not too expert in django. is django channel is good choice for that . and if  u know any tutorials on that please recommend me. thanks in advance

**Comment by ryanhiebert** [comment]
Django Channels seems like a pretty good choice for that work. You'll need to find a way to namespace private message channels. I don't have any particular suggestions on that, but it's actually similar to a personal project that I'll be working on pretty soon. I'd be interested to see what you come up with, if you're able to show me.

Also, this is the issue tracker for HireFire python tracking. We don't even have Django Channels support yet, because no-one has implemented it yet.

**Comment by rahul6612** [comment]
i already created an app where peoples can post their messages(text/audio/videos)they can follow/unfollow like/unlike posts etc. and a e-commerce website Now i want to add messaging feature on my project but no idea about it.

**Comment by ryanhiebert** [comment]
I'm afraid I'm really not in a position to help out with learning Django Channels, and this isn't the right issue tracker to get help. I'm not entirely sure which one to point you to, but you might ask over at `#django` on Freenode, that seems like a relatively good starting place to potentially find someone that would be able to assist you.

**Comment by rahul6612** [comment]
ok thanks for your precious time.
