### ISSUE TITLE
Middleware hanging for Django 2

### ISSUE THREAD

**Issue by tspecht** [ryanhiebert/hirefire#45]
Hey!

I have been using the plugin for a long time, since I upgraded to 0.6 and Django 2 the middleware returns timeouts unfortunately and isn't usable anymore. I have tried to debug this on my own, but for some reason it doesn't seem to like celery and kombu well. I have other apps running the same version of celery and kombu but Django 1.9 + Hirefire 0.3 and it works well there. Any idea?

Output of `pip freeze`:
```
amqp==2.3.2
celery==4.2.1
Django==2.0.2
HireFire==0.6
kombu==4.2.1
```

**Comment by ryanhiebert** [comment]
Are you able to determine which version of this package broke it for you?

**Comment by tspecht** [comment]
@ryanhiebert that should be 0.5, I can't test below because Django 2 doesn't work with it unfortunately. Any idea where I could start digging into this? I suspect AMQP being the issue but that's just a very rough guess

**Comment by ryanhiebert** [comment]
Well, in 0.4 I introduced a new feature that can severely slow down the check when there are large numbers of workers running. It's been workable for me, though not quick, with upwards of 50 workers. How many workers are you running? Could that be your issue? If so, you can change it back from the new default to what was the default previously, as noted here for `inspect_statuses`: https://hirefire.readthedocs.io/en/stable/procs/.

**Comment by codingjoe** [comment]
@ryanhiebert that begs the questions of this feature really should be enabled by default. I do see the use case for it – we are using it for an on/off queue ourselves but I disabled it for anything else.
I would recommend to disable it by default and add a big chunk of documentation for it.

**Comment by ryanhiebert** [comment]
That's a fair question, which I gave thought to before making it the default, especially given that it wasn't the default before. The flip side is whether it's really OK to have the wrong answer by default. We're choosing between two bad options: wrong and slow. I prefer to default to correct than fast. And I'd prefer it be fast, if we can make it so, but I haven't found a way to do that yet.

@tspecht : can you confirm that you have a large number of workers, which would make it likely that this is your issue?

**Comment by codingjoe** [comment]
@ryanhiebert I agree with your point. I believe it boils down to documentation then. I also don't see a reason the change the default now.

**Comment by ryanhiebert** [comment]
The bad behavior is scaling down before the tasks are done. Which, without the new inspect statuses, happened to me _all the time_. It consistently did the wrong thing. I'd definitely love some better documentation. Perhaps a note in the readme about this potential gotcha at scale.

BTW, are you using this on Heroku? I've run with >40 dynos, and while quite slow, it does return before Heroku's timeout most of the time. You're using the term "machine" which has me wondering if you're using it with Heroku dynos. I've personally stopped using HireFire, which has made me think about separating the HireFire output from the stats gathering functionality.

**Comment by tspecht** [comment]
Yeah, we are running on Heroku and disabled ACKS_LATE for celery to work around these kind of issues. Out of interest, if you are not using Hirefire anymore, what are you using then to scale now?

**Comment by ryanhiebert** [comment]
How does disabling `acks_late` make things better? It would make it so that as soon as it's out of the queue, rabbitmq sees it as complete.

We are now having our app scale itself based on the metrics created in this HireFire package. We needed to do similar scaling for a non-Heroku platform, so HireFire itself wouldn't work for it, and it was easier to write to Heroku's API and the other API than to work through HireFire for one system, and through the other API on the other system. We have a task that runs every minute, similar to HireFire, checks the metrics, and then interacts with the Heroku API directly.

**Comment by ryanhiebert** [comment]
I think that the correctness issue means that the default needs to stay as is. Docs improvements are welcome.

**Comment by Rawgeek** [comment]
In Django setting `BROKER_POOL_LIMIT = 1` hangs `app.control.inspect().active()` when using with AMQP

**Comment by codingjoe** [comment]
> In Django setting `BROKER_POOL_LIMIT = 1` hangs `app.control.inspect().active()` when using with AMQP

Hi @Rawgeek, I am not entirely sure this is a hirefire issue. You changed a Celery package, and now Celery inspect hangs... that does sound like a Celery issue 🤔
Also remind me, why would you set the [broker_pool_limit](https://docs.celeryproject.org/en/latest/userguide/configuration.html#std:setting-broker_pool_limit) to `1`? That would indeed allow a pool to only open a single connection. This might keep it from accepting the incoming connection via the inspect call. Are you sure you didn't mean it to be set to `None`?

**Comment by Rawgeek** [comment]
Thanks for quick response. I've posted to celery issue here:
https://github.com/celery/celery/issues/5139

I just thought this could be useful to someone having similar issue.

The reason to set it to 1 is to reduce the number of connections recommended by CloudAMQP here: https://www.cloudamqp.com/docs/celery.html

Although it makes sense on their cheaper plans as they limit how many concurrent connections you're allowed, it doesn't make sense on a higher plans as those support over 5,000.

**Comment by codingjoe** [comment]
@Rawgeek as you correctly stated, this is just an example setting. I would advise to go with one of their dedicated instances. It will provide you with plenty connections.
The connection pool is an important feature to reduce IO and latency, since TCP transports are being reused. Please don't use the formula on CloudAMQPs website to determine the correct number of connection. It is not correct. Komubu handles connection pools in celery and it does not work as described.

I have been using CloudAMQP for half a decade now in production. I never ran into any problems with too many connections. I would suggest to simply drop the setting all together.
